# Generated by Django 5.0.7 on 2024-07-19 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "imdb_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.CharField(max_length=240)),
                ("year", models.IntegerField(null=True)),
                ("poster_url", models.URLField(blank=True, null=True)),
                ("actors", models.CharField(blank=True, max_length=2056)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("body", models.TextField()),
                ("background", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="EpicQuotes.movie",
                    ),
                ),
            ],
        ),
    ]
